### ISSUE TITLE
Mixed up results using the `frac` calculation method

### ISSUE THREAD

**Issue by kasra-keshavarz** [kasra-keshavarz/gistool#12]
The results were mixed up as described in the following: https://github.com/isciences/exactextractr/issues/89

The issue has been raised by Cooper Albano and @AlaBahrami originally.

**Comment by ShervanGharari** [comment]
did the `exactextractr` update fixed the issue?

**Comment by kasra-keshavarz** [comment]
Yes! Does it matter?

**Comment by ShervanGharari** [comment]
Just to know if the issue was fully from `exactextractr` and not `gistool`. glad it is resolved, and thank you.

**Comment by AlaBahrami** [comment]
Thanks a lot @kasra-keshavarz . It sounds cool. I should try a test. It supposed to be `**exactextractr** ` bug issue. I saw the modifications they have applied.
